version: "3.9"
services:
 web:
    build: .
    ports:
      - "8000:8000"  
    environment:
      DB_NAME: lodge
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: db
      DB_PORT: 5432 
      SECRET_KEY: '2232b1ec1b426bc383f1ec071979d87dd91e7b2e8467a5e0620e714ee1affdc5'
      EMAIL_USER: lodge417.form@gmail.com
      EMAIL_PASS: agetrjlkwjsestkr
      EMAIL_TO: lodge417.form@gmail.com
    depends_on:
      - db
    volumes:
      - .:/app

 db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: lodge
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

